# Generated by Django 2.2.6 on 2020-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.IntegerField(verbose_name='脚本id')),
                ('public', models.IntegerField(verbose_name='来源')),
                ('script_type', models.IntegerField(verbose_name='类型')),
                ('name', models.TextField(verbose_name='名字')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(verbose_name='完成时间')),
                ('bk_biz_id', models.IntegerField(null=True, verbose_name='业务id')),
            ],
        ),
    ]
