# Generated by Django 2.2.6 on 2020-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务ID')),
                ('bk_biz_name', models.CharField(max_length=50, verbose_name='业务名称')),
                ('job_instance_id', models.IntegerField(verbose_name='作业ID')),
                ('job_instance_name', models.TextField(verbose_name='作业名称')),
                ('ip_list', models.CharField(max_length=1000, verbose_name='主机列表')),
                ('script_id', models.IntegerField(verbose_name='脚本')),
                ('script_name', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('job_status', models.IntegerField(verbose_name='作业状态')),
                ('execute_time', models.DateTimeField(verbose_name='执行时间')),
                ('end_time', models.DateTimeField(verbose_name='完成时间')),
                ('bk_job_log', models.TextField(null=True, verbose_name='日志')),
            ],
        ),
    ]
